### ISSUE TITLE
Fields.py has problems in 2.1.28+

### ISSUE THREAD

**Issue by natfarleydev** [natfarleydev/anki-auto-markdown#1]
Anki produces the following error when attempting to look at the fields of a card:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.30 (06a69c25) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-18 11:23:49
Add-ons possibly involved: ⁨Auto Markdown - fix version⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/models.py", line 168, in onFields
  File "/home/nasfarley88/.local/share/Anki2/addons21/15061497/fields.py", line 18, in fieldDialog__init__
    self.model = note.model()
AttributeError: 'dict' object has no attribute 'model'

```

**Comment by dummifiedme** [comment]
> 
> 
> Anki produces the following error when attempting to look at the fields of a card:
> 
> ```
> Error 
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
> If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
> When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
> Debug info:
> Anki 2.1.30 (06a69c25) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
> Platform: Linux
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2020-08-18 11:23:49
> Add-ons possibly involved: ⁨Auto Markdown - fix version⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt/models.py", line 168, in onFields
>   File "/home/nasfarley88/.local/share/Anki2/addons21/15061497/fields.py", line 18, in fieldDialog__init__
>     self.model = note.model()
> AttributeError: 'dict' object has no attribute 'model'
> ```

I have the same issue.

**Comment by natfarleydev** [comment]
Problem has been caused by the monkey-patched method `FieldDialog.__init__` changing from:

https://github.com/ankitects/anki/blob/70784154059a16805936ffa107e52e99cf46f43d/qt/aqt/fields.py#L12 
```python
class FieldDialog(QDialog):
    def __init__(self, mw, note, ord=0, parent=None):
```

to 

https://github.com/ankitects/anki/blob/06a69c25e67cc6f08abb311d2964e32a34361b34/qt/aqt/fields.py#L16
```python
class FieldDialog(QDialog):
    def __init__(self, mw: AnkiQt, nt: NoteType, parent=None):
```
