### ISSUE TITLE
Can I use cloze?

### ISSUE THREAD

**Issue by ghost** [natfarleydev/anki-auto-markdown#19]
I want a feature that I can use cloze in function lines like :
```js
{{c1:def}} = function(){
}
```
There is already "Markdown and KaTeX Support" addon, but yours is more convenient to me.
Can you make it?

**Comment by natfarleydev** [comment]
Hi,
Unfortunately this plugin is maintenance only so I won't be adding new features. If someone wants to make a PR making cloze's easier with markdown, they are more than welcome!

Personally, I just make the cloze _after_ converting to markdown. The cloze is lost when converting back from markdown, but I rarely use clozes with markdown so I don't find it an issue.
